// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#ifndef _FUTURISTIC_EBIKE_UI_H
#define _FUTURISTIC_EBIKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void Particle1_Animation( lv_obj_t *TargetObject, int delay);
void Particle2_Animation( lv_obj_t *TargetObject, int delay);
void Particle3_Animation( lv_obj_t *TargetObject, int delay);
void Fash_Animation( lv_obj_t *TargetObject, int delay);
void Wave1_Animation( lv_obj_t *TargetObject, int delay);
void Wave2_Animation( lv_obj_t *TargetObject, int delay);
void Off_Animation( lv_obj_t *TargetObject, int delay);
void On_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Driving
void ui_Driving_screen_init(void);
extern lv_obj_t *ui_Driving;
extern lv_obj_t *ui_Speed_Number_2;
extern lv_obj_t *ui_Speed_Number_1;
extern lv_obj_t *ui_Label_Speed;
extern lv_obj_t *ui_Label_kmh1;
extern lv_obj_t *ui_Group_Battery_Percent;
extern lv_obj_t *ui_Label_Number1;
extern lv_obj_t *ui_Label_Number2;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Label_Number3;
extern lv_obj_t *ui_Label_Number4;
extern lv_obj_t *ui_Label_Number5;
extern lv_obj_t *ui_Label_Battery;
extern lv_obj_t *ui_Label_Celsius;
extern lv_obj_t *ui_Group_Footer;
extern lv_obj_t *ui_Label_Battery_Number;
extern lv_obj_t *ui_Label_Battery_Percent;
extern lv_obj_t *ui_Group_Driving;
extern lv_obj_t *ui_Group_Title;
extern lv_obj_t *ui_Label_Driving_Information;
extern lv_obj_t *ui_Group_Content;
extern lv_obj_t *ui_Label_Temp;
extern lv_obj_t *ui_Group_ODO;
extern lv_obj_t *ui_LabeL_ODO;
extern lv_obj_t *ui_Label_ODOx;
extern lv_obj_t *ui_Label_ODOy;
extern lv_obj_t *ui_Label_comma;
extern lv_obj_t *ui_Group_Trip;
extern lv_obj_t *ui_Label_Trip;
extern lv_obj_t *ui_Label_Trip_Number;
extern lv_obj_t *ui_Label_km2;
extern lv_obj_t *ui_Group_Max_Speed;
extern lv_obj_t *ui_Label_Max_Speed;
extern lv_obj_t *ui_Label_Max_Speed_Number;
extern lv_obj_t *ui_Label_kmh2;
extern lv_obj_t *ui_Group_Time;
extern lv_obj_t *ui_Label_Time1;
extern lv_obj_t *ui_Label_Runtime;
extern lv_obj_t *ui____initial_actions0;

LV_FONT_DECLARE( ui_font_Big);
LV_FONT_DECLARE( ui_font_Medium);
LV_FONT_DECLARE( ui_font_Number);
LV_FONT_DECLARE( ui_font_Small);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
