// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Futuristic_Ebike

#include "../ui.h"
#include "selector.h"

void ui_Driving_screen_init(void){
ui_Driving = lv_obj_create(selector::miscTab);
lv_obj_clear_flag( ui_Driving, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Driving, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Driving, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Number_2 = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Speed_Number_2, 100);
lv_obj_set_height( ui_Speed_Number_2, 100);
lv_obj_set_x( ui_Speed_Number_2, -90 );
lv_obj_set_y( ui_Speed_Number_2, 8 );
lv_obj_set_align( ui_Speed_Number_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed_Number_2,"32");
lv_obj_set_style_text_color(ui_Speed_Number_2, lv_color_hex(0xD56920), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed_Number_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed_Number_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_Number_2, &ui_font_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Number_1 = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Speed_Number_1, 100);
lv_obj_set_height( ui_Speed_Number_1, 100);
lv_obj_set_x( ui_Speed_Number_1, -100 );
lv_obj_set_y( ui_Speed_Number_1, 8 );
lv_obj_set_align( ui_Speed_Number_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed_Number_1,"32");
lv_obj_set_style_text_color(ui_Speed_Number_1, lv_color_hex(0xFFE69C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed_Number_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed_Number_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_Number_1, &ui_font_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Speed = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Label_Speed, 100);
lv_obj_set_height( ui_Label_Speed, 15);
lv_obj_set_x( ui_Label_Speed, -100 );
lv_obj_set_y( ui_Label_Speed, -45 );
lv_obj_set_align( ui_Label_Speed, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Speed,"Drive Speed");
lv_obj_set_style_text_color(ui_Label_Speed, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Speed, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_kmh1 = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Label_kmh1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_kmh1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_kmh1, -13 );
lv_obj_set_y( ui_Label_kmh1, 58 );
lv_obj_set_align( ui_Label_kmh1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_kmh1,"km/h");
lv_obj_set_style_text_color(ui_Label_kmh1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_kmh1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_kmh1, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Battery_Percent = lv_obj_create(ui_Driving);
lv_obj_set_width( ui_Group_Battery_Percent, 100);
lv_obj_set_height( ui_Group_Battery_Percent, 200);
lv_obj_set_align( ui_Group_Battery_Percent, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Group_Battery_Percent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Battery_Percent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Battery_Percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number1 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Number1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number1,"100#94aeb4 %");
lv_label_set_recolor(ui_Label_Number1,"true");
lv_obj_set_style_text_color(ui_Label_Number1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number1, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number2 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number2, 0 );
lv_obj_set_y( ui_Label_Number2, lv_pct(22) );
lv_obj_set_align( ui_Label_Number2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number2,"75#94aeb4 %");
lv_label_set_recolor(ui_Label_Number2,"true");
lv_obj_set_style_text_color(ui_Label_Number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number2, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_Group_Battery_Percent);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, lv_pct(5));
lv_obj_set_height( ui_Bar2, lv_pct(100));
lv_obj_set_x( ui_Bar2, 25 );
lv_obj_set_y( ui_Bar2, 0 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xEABB37), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0xEABB37), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar2, 125, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Bar2, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xEABB37), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0xEABB37), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar2, 125, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Bar2, LV_BORDER_SIDE_BOTTOM, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_Group_Battery_Percent);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, lv_pct(10));
lv_obj_set_height( ui_Bar1, lv_pct(100));
lv_obj_set_x( ui_Bar1, 20 );
lv_obj_set_y( ui_Bar1, 0 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x33B1D4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x33B1D4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar1, 125, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Bar1, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x33B1D4), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x33B1D4), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar1, 125, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Bar1, LV_BORDER_SIDE_BOTTOM, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label_Number3 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number3, 0 );
lv_obj_set_y( ui_Label_Number3, lv_pct(50) );
lv_obj_set_align( ui_Label_Number3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number3,"50#94aeb4 %");
lv_label_set_recolor(ui_Label_Number3,"true");
lv_obj_set_style_text_color(ui_Label_Number3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number3, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number4 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number4, 0 );
lv_obj_set_y( ui_Label_Number4, lv_pct(74) );
lv_obj_set_align( ui_Label_Number4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number4,"25#94aeb4 %");
lv_label_set_recolor(ui_Label_Number4,"true");
lv_obj_set_style_text_color(ui_Label_Number4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number4, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number5 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number5, 0 );
lv_obj_set_y( ui_Label_Number5, lv_pct(94) );
lv_obj_set_align( ui_Label_Number5, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number5,"0#94aeb4 %");
lv_label_set_recolor(ui_Label_Number5,"true");
lv_obj_set_style_text_color(ui_Label_Number5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number5, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Battery = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Label_Battery, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Battery, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Battery, 0 );
lv_obj_set_y( ui_Label_Battery, 10 );
lv_label_set_text(ui_Label_Battery,"Battery");
lv_obj_set_style_text_color(ui_Label_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Battery, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Celsius = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Label_Celsius, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Celsius, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Celsius, 100 );
lv_obj_set_y( ui_Label_Celsius, 10 );
lv_label_set_text(ui_Label_Celsius,"°C");
lv_obj_set_style_text_color(ui_Label_Celsius, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Celsius, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Celsius, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Footer = lv_obj_create(ui_Driving);
lv_obj_set_height( ui_Group_Footer, 40);
lv_obj_set_width( ui_Group_Footer, lv_pct(100));
lv_obj_set_align( ui_Group_Footer, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Group_Footer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Footer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Battery_Number = lv_label_create(ui_Group_Footer);
lv_obj_set_width( ui_Label_Battery_Number, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Battery_Number, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Battery_Number, -424 );
lv_obj_set_y( ui_Label_Battery_Number, 7 );
lv_obj_set_align( ui_Label_Battery_Number, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Battery_Number,"100");
lv_obj_set_style_text_color(ui_Label_Battery_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Battery_Number, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Battery_Number, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Battery_Number, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Battery_Percent = lv_label_create(ui_Group_Footer);
lv_obj_set_width( ui_Label_Battery_Percent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Battery_Percent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Battery_Percent, 58 );
lv_obj_set_y( ui_Label_Battery_Percent, 4 );
lv_obj_set_align( ui_Label_Battery_Percent, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_Battery_Percent,"%");
lv_obj_set_style_text_color(ui_Label_Battery_Percent, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Battery_Percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Battery_Percent, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Driving = lv_obj_create(ui_Driving);
lv_obj_set_width( ui_Group_Driving, 260);
lv_obj_set_height( ui_Group_Driving, 200);
lv_obj_set_x( ui_Group_Driving, 0 );
lv_obj_set_y( ui_Group_Driving, -10 );
lv_obj_set_align( ui_Group_Driving, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Group_Driving, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Driving, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Driving, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Title = lv_obj_create(ui_Group_Driving);
lv_obj_set_width( ui_Group_Title, 260);
lv_obj_set_height( ui_Group_Title, 46);
lv_obj_set_align( ui_Group_Title, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Group_Title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Title, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Driving_Information = lv_label_create(ui_Group_Title);
lv_obj_set_width( ui_Label_Driving_Information, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Driving_Information, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Driving_Information, lv_pct(-7) );
lv_obj_set_y( ui_Label_Driving_Information, lv_pct(30) );
lv_obj_set_align( ui_Label_Driving_Information, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Driving_Information,"Drive Information");
lv_obj_set_style_text_color(ui_Label_Driving_Information, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Driving_Information, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Driving_Information, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Content = lv_obj_create(ui_Group_Driving);
lv_obj_set_width( ui_Group_Content, 200);
lv_obj_set_height( ui_Group_Content, 154);
lv_obj_set_align( ui_Group_Content, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_Group_Content, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Content, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Group_Content, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Group_Content, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Group_Content, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Group_Content, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Temp = lv_label_create(ui_Group_Content);
lv_obj_set_width( ui_Label_Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Temp, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Temp,"+24.7");
lv_obj_set_style_text_color(ui_Label_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Temp, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_ODO = lv_obj_create(ui_Group_Content);
lv_obj_set_width( ui_Group_ODO, 80);
lv_obj_set_height( ui_Group_ODO, 40);
lv_obj_set_align( ui_Group_ODO, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Group_ODO, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_ODO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_ODO, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Group_ODO, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Group_ODO, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Group_ODO, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Group_ODO, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabeL_ODO = lv_label_create(ui_Group_ODO);
lv_obj_set_width( ui_LabeL_ODO, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabeL_ODO, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LabeL_ODO,"ODO");
lv_obj_set_style_text_color(ui_LabeL_ODO, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabeL_ODO, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabeL_ODO, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_ODOx = lv_label_create(ui_Group_ODO);
lv_obj_set_width( ui_Label_ODOx, lv_pct(25));
lv_obj_set_height( ui_Label_ODOx, lv_pct(25));
lv_obj_set_x( ui_Label_ODOx, 2 );
lv_obj_set_y( ui_Label_ODOx, 6 );
lv_obj_set_align( ui_Label_ODOx, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_ODOx,"287.7");
lv_obj_set_style_text_color(ui_Label_ODOx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_ODOx, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_ODOx, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_ODOy = lv_label_create(ui_Group_ODO);
lv_obj_set_width( ui_Label_ODOy, lv_pct(25));
lv_obj_set_height( ui_Label_ODOy, lv_pct(25));
lv_obj_set_x( ui_Label_ODOy, 30 );
lv_obj_set_y( ui_Label_ODOy, 6 );
lv_obj_set_align( ui_Label_ODOy, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_ODOy,"287.7");
lv_obj_set_style_text_color(ui_Label_ODOy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_ODOy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_ODOy, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_comma = lv_label_create(ui_Group_ODO);
lv_obj_set_width( ui_Label_comma, lv_pct(25));
lv_obj_set_height( ui_Label_comma, lv_pct(25));
lv_obj_set_x( ui_Label_comma, 23 );
lv_obj_set_y( ui_Label_comma, 11 );
lv_obj_set_align( ui_Label_comma, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_comma,"'");
lv_obj_set_style_text_color(ui_Label_comma, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_comma, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_comma, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Trip = lv_obj_create(ui_Group_Content);
lv_obj_set_width( ui_Group_Trip, 80);
lv_obj_set_height( ui_Group_Trip, 40);
lv_obj_clear_flag( ui_Group_Trip, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Trip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Trip, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Group_Trip, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Group_Trip, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Group_Trip, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Group_Trip, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Trip = lv_label_create(ui_Group_Trip);
lv_obj_set_width( ui_Label_Trip, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Trip, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label_Trip,"TRIP");
lv_obj_set_style_text_color(ui_Label_Trip, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Trip, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Trip, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Trip_Number = lv_label_create(ui_Group_Trip);
lv_obj_set_width( ui_Label_Trip_Number, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Trip_Number, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Trip_Number, 2 );
lv_obj_set_y( ui_Label_Trip_Number, 6 );
lv_obj_set_align( ui_Label_Trip_Number, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_Trip_Number,"18.6");
lv_obj_set_style_text_color(ui_Label_Trip_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Trip_Number, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Trip_Number, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_km2 = lv_label_create(ui_Group_Trip);
lv_obj_set_width( ui_Label_km2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_km2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_km2, -20 );
lv_obj_set_y( ui_Label_km2, -5 );
lv_obj_set_align( ui_Label_km2, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Label_km2,"km");
lv_obj_set_style_text_color(ui_Label_km2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_km2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_km2, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Max_Speed = lv_obj_create(ui_Group_Content);
lv_obj_set_width( ui_Group_Max_Speed, 82);
lv_obj_set_height( ui_Group_Max_Speed, 40);
lv_obj_set_align( ui_Group_Max_Speed, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Group_Max_Speed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Max_Speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Max_Speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Group_Max_Speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Group_Max_Speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Group_Max_Speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Group_Max_Speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Max_Speed = lv_label_create(ui_Group_Max_Speed);
lv_obj_set_width( ui_Label_Max_Speed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Max_Speed, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label_Max_Speed,"MAX. SPEED");
lv_obj_set_style_text_color(ui_Label_Max_Speed, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Max_Speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Max_Speed, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Max_Speed_Number = lv_label_create(ui_Group_Max_Speed);
lv_obj_set_width( ui_Label_Max_Speed_Number, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Max_Speed_Number, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Max_Speed_Number, 2 );
lv_obj_set_y( ui_Label_Max_Speed_Number, 6 );
lv_obj_set_align( ui_Label_Max_Speed_Number, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_Max_Speed_Number,"42.7");
lv_obj_set_style_text_color(ui_Label_Max_Speed_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Max_Speed_Number, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Max_Speed_Number, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_kmh2 = lv_label_create(ui_Group_Max_Speed);
lv_obj_set_width( ui_Label_kmh2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_kmh2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_kmh2, -6 );
lv_obj_set_y( ui_Label_kmh2, -5 );
lv_obj_set_align( ui_Label_kmh2, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Label_kmh2,"km/h");
lv_obj_set_style_text_color(ui_Label_kmh2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_kmh2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_kmh2, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Time = lv_obj_create(ui_Group_Content);
lv_obj_set_width( ui_Group_Time, 80);
lv_obj_set_height( ui_Group_Time, 40);
lv_obj_set_align( ui_Group_Time, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_Group_Time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Group_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Group_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Group_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Group_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Time1 = lv_label_create(ui_Group_Time);
lv_obj_set_width( ui_Label_Time1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Time1, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label_Time1,"Run Time");
lv_obj_set_style_text_color(ui_Label_Time1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Time1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Time1, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Runtime = lv_label_create(ui_Group_Time);
lv_obj_set_width( ui_Label_Runtime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Runtime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Runtime, 2 );
lv_obj_set_y( ui_Label_Runtime, 6 );
lv_obj_set_align( ui_Label_Runtime, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_Runtime,"00:05:36");
lv_obj_set_style_text_color(ui_Label_Runtime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Runtime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Runtime, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);
}
